default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: depot_development

test:
  <<: *default
  database: depot_test

production:
  <<: *default
  database: depot_production
